/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogCard: typeof import('./components/BlogCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/svg/Login.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./components/svg/SignUp.vue')['default']
    TopIndex: typeof import('./components/TopIndex.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserList: typeof import('./components/userList.vue')['default']
  }
}
